namespace: shellclear
name: aap
version: 1.0.0
readme: README.md
authors:
- shelclear <shellclear@gmail.com>
description: AAP
license:
- 'GPL-2.0-or-later'
dependencies:
  community.general: '>=5.0.2'
repository: https://github.com/shellclear/aap
