namespace: shellclear
name: ansible_collection_aap
version: 1.0.0
readme: README.md
authors:
- shelclear <shellclear@gmail.com>
description: Ansible collection to automate AAP related tasks
license:
- 'GPL-3.0-or-later'
dependencies:
  "community.general": ">=5.5.0"
repository: https://github.com/shellclear/ansible_collection_aap
issues: https://github.com/shellclear/ansible_collection_aap/issues
tags:
  - automation_platform
  - aap
  - ansible
