---
# tasks file for aap_requirements_check
- name: Ensure ansible user ({{ ansible_username }}) exists
  ansible.builtin.user: 
    name: "{{ ansible_username }}"
    state: present
    password: "{{ ( ansible_user_password | mandatory ) | password_hash('sha512') }}"

- name: Ensure ansible user ({{ ansible_username }}) is able to run commands as root
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ ansible_username }}
    state: present
    create: true
    line: '{{ ansible_username }} ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

- name: Ensure ansible user ({{ ansible_username  }}) ssh public key is allowed on the nodes
  when: authorized_ssh_pub_key_ansible_user is defined
  ansible.posix.authorized_key:
    user: "{{ ansible_username }}"
    state: present
    key: "{{ authorized_ssh_pub_key_ansible_user }}"